name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy FastAPI Backend
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'dse-nps'
          
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: 'dse-nps'

      - name: Verify authentication
        run: gcloud auth list

      - name: Set environment variable for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Build and Deploy to Cloud Run
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
            gcloud builds submit \
              --config deployment/prod-cloudbuild.yml \
              --service-account=github-actions-sa@dse-nps.iam.gserviceaccount.com \
              .
            
            gcloud run deploy fire-recovery-backend-prod \
              --image us-central1-docker.pkg.dev/dse-nps/fire-recovery-backend/prod:latest \
              --platform managed \
              --service-account=github-actions-sa@dse-nps.iam.gserviceaccount.com \
              --region us-central1
          fi

          if [ "${{ env.BRANCH_NAME }}" = "dev" ]; then
            gcloud builds submit \
              --config deployment/dev-cloudbuild.yml \
              --service-account=github-actions-sa@dse-nps.iam.gserviceaccount.com \
              .
            
            gcloud run deploy fire-recovery-backend-dev \
              --image us-central1-docker.pkg.dev/dse-nps/fire-recovery-backend/dev:latest \
              --platform managed \
              --service-account=github-actions-sa@dse-nps.iam.gserviceaccount.com \
              --region us-central1
          fi