name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy FastAPI Backend
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/113009620257/locations/global/workloadIdentityPools/github-actions-prod/providers/oidc-provider-prod"
          project_id: "dse-nps"
          service_account: "github-actions-sa-prod@dse-nps.iam.gserviceaccount.com"
          token_format: "access_token"
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify authentication
        run: gcloud auth list

      - name: Set environment variable for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Update cloudbuild files
        run: |
          sed -i 's/fastapi.Dockerfile/coiled.Dockerfile/g' deployment/prod-cloudbuild.yml
          sed -i 's/fastapi.Dockerfile/coiled.Dockerfile/g' deployment/dev-cloudbuild.yml

      - name: Build and Deploy to Cloud Run
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
            # Production build and deploy
            echo "Deploying production environment"
            gcloud builds submit --config deployment/prod-cloudbuild.yml . || {
              echo "Error submitting build. Checking permissions..."
              gcloud projects get-iam-policy dse-nps --format=json | grep -A 5 "github-actions-sa-prod"
              exit 1
            }
            
            gcloud run deploy fire-recovery-backend-prod \
              --image us-central1-docker.pkg.dev/dse-nps/fire-recovery-backend/prod:latest \
              --platform managed \
              --region us-central1
          fi

          if [ "${{ env.BRANCH_NAME }}" = "dev" ]; then
            # Development build and deploy
            echo "Deploying development environment"
            gcloud builds submit --config deployment/dev-cloudbuild.yml . || {
              echo "Error submitting build. Checking permissions..."
              gcloud projects get-iam-policy dse-nps --format=json | grep -A 5 "github-actions-sa-prod"
              exit 1
            }
            
            gcloud run deploy fire-recovery-backend-dev \
              --image us-central1-docker.pkg.dev/dse-nps/fire-recovery-backend/dev:latest \
              --platform managed \
              --region us-central1
          fi